### ISSUE TITLE
pcap2csv.sh return nothing 

### ISSUE THREAD

**Issue by csmibrahim** [watalabo/WiPiCap#1]
Thank you for sharing your scripts online 

I tried pcap2csv.sh on windows with pcap file extracted from RPI. I get empty csv file with -Y 'wlan.fc.type_subtype == 0x000e' . Or when I remove this part from the command I get only the time in the csv. 

How I can get the CSI information?  Thanks

**Comment by koushik1207** [comment]
Hi, I am also facing the same issue. Were you able to solve it?

**Comment by dev-sora** [comment]
Thanks for your kind reporting.  In fact, the scripts currently are really miscellaneous things, and we have updated ones used in our research but not on GitHub.
I'm really sorry for leaving things incomplete.  We will update all scripts in next few weeks, so please be patient.
