### ISSUE TITLE
 how to use iperf or ping to send UDP packets from Raspberry Pi to devices. 

### ISSUE THREAD

**Issue by azuryl** [watalabo/WiPiCap#2]
hello 
thank you great job
as I know In monitor mode,  wireless network interface card (NIC) can passively listen to all wireless traffic on a particular wireless channel without participating in any network communications. so I want to know  how to use iperf or ping to send UDP packets from Raspberry Pi to devices.

**Comment by dev-sora** [comment]
Dear azuryl,

Sorry for late reply.... too late, actually, but I reply to your message while hoping this answer helps not only you but others having the same question.

In general, your understanding is correct that NIC in monitor mode can listen to any wireless traffic around.  What we did in our experiment is:
1. Prepare one router (as Tx), one device (as Rx) and one sniffer device in monitor mode
2. Associate the Rx device and the router
3. Use iperf or ping to make packet flow from the Rx to the Tx (and vice versa).
4. Sniffer once collect any communication around it, then we filter out unnecessary packet but retain packets between our Rx and Tx based on MAC address.

and we consider that's the only way.

I hope this answer helps you well!

**Comment by dev-sora** [comment]
This issue have no additional comments and questions from the questioner after the author replied for about 6 months, so let us close for now.  Thanks for your attention to our project!
